<a href="https://colab.research.google.com/github/minhtam3010050-jpg/TH_DEEP/blob/main/BT_TUAN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#3.1
import numpy as np
my_list = [1,9,15,39]
print('Python list:',my_list)

my_numpy_array = np.array(my_list)
print('Numpy array:',my_numpy_array)

#cach 2
a=np.array([1,9,15,39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
#3.2 2 chiều
c = np.array([(1,2,3),
              (4,5,6)])
print(c)
print(c.shape)
print(c.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#3.3 Mảng 3 chiều
d = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10,11,12]]
              ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
#3.4 Tạo mảng với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix:\n',f)


Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
#3.5.1
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10.,11.,12.]]
            ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape(3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape(3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape(2,3,2)\n',k)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape(3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape(3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape(2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]
