<a href="https://colab.research.google.com/github/minhtam3010050-jpg/TH_DEEP/blob/main/BT_TUAN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY


In [ ]:
#3.1
import numpy as np
my_list = [1,9,15,39]
print('Python list:',my_list)

my_numpy_array = np.array(my_list)
print('Numpy array:',my_numpy_array)

#cach 2
a=np.array([1,9,15,39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
#3.2 2 chiều
c = np.array([(1,2,3),
              (4,5,6)])
print(c)
print(c.shape)
print(c.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
#3.3 Mảng 3 chiều
d = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10,11,12]]
              ])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [ ]:
#3.4 Tạo mảng với giá trị ban đầu là 0 hoặc 1
e=np.zeros((2,2))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix:\n',f)


Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#3.5.1
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10.,11.,12.]]
            ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape(3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape(3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape(2,3,2)\n',k)


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape(3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape(3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape(2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [ ]:
#3.5.2
e=np.array([[1.,2.,3.],[4.,5.,6.]])
f=e.flatten()
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10.,11.,12.]]
            ])
j=g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
#3.6
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
#3.7.1. Sinh mảng số nguyên ngẫu nhiên

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [14 98 90  4 88]
Random 2-D array
 [[28 11 47 27]
 [60  7 79 58]
 [29  9 39  6]]
Random 3-D array
 [[[37 58 53]
  [47 95 80]
  [88 90  0]
  [82 38 81]]

 [[61 33 52]
  [27 21 84]
  [16 15 79]
  [89 73 10]]

 [[40 42  7]
  [44 84 77]
  [32 74 28]
  [18  0 48]]]


In [ ]:
#3.7.2. Sinh mảng số thực trong khoảng [0, 1]

a = np.random.rand(5)
print('Random 1-D array\n', a)

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)

Random 1-D array
 [0.79871597 0.39021965 0.44842019 0.64261965 0.56671648]
Random 2-D array
 [[0.08842748 0.92469481 0.87428316 0.06550367]
 [0.83549595 0.83026221 0.4308644  0.90773951]
 [0.21265956 0.26984416 0.74888369 0.36139955]]
Random 3-D array
 [[[0.61006975 0.15313194 0.45770142]
  [0.50702246 0.86409206 0.24386485]
  [0.66957321 0.63714306 0.07312007]
  [0.80374742 0.52810427 0.21500681]]

 [[0.18047175 0.61161609 0.06479408]
  [0.40999079 0.94945219 0.08715542]
  [0.01561042 0.31275585 0.20646659]
  [0.50272827 0.46791213 0.04819078]]

 [[0.00697229 0.15771498 0.81473932]
  [0.94876901 0.60521672 0.62188321]
  [0.01117032 0.92606946 0.94557067]
  [0.71405762 0.98800972 0.65422375]]]


3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
a=np.random.normal(5,0.5,10)
print(a)

[4.53031274 4.90924214 5.0180282  5.25577055 4.53390051 5.460344
 4.14653063 4.83842959 5.03698562 4.4763976 ]


3.8. Thay đổi giá trị của ma trận

In [ ]:

A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)

np.array(A)[2] = 2
print('Change values of third row with array\n', A)

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.9. Sinh dãy số theo khoảng cho trước

In [ ]:
#3.9.1. Dùng hàm arange
a = np.arange(1, 20)
print('Dãy số từ 1 đến 19:\n', a)

b = np.arange(1, 20, 2)
print('Dãy số bước nhảy là 2:\n', b)

#3.9.2. Dùng hàm linspace
c = np.linspace(1., 5., num=10)
print('Dãy 10 số chia đều từ 1 đến 5:\n', c)

Dãy số từ 1 đến 19:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Dãy số bước nhảy là 2:
 [ 1  3  5  7  9 11 13 15 17 19]
Dãy 10 số chia đều từ 1 đến 5:
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


3.10. Index và slice

In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print('Ma trận a:\n', a)

print('first row:', a[0])
print('second row:', a[1])

print('Second column:', a[:, 1])
print('First column:', a[:, 0])
print('First two values of second row:', a[1, :2])

Ma trận a:
 [[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
First column: [1 4]
First two values of second row: [4 5]


**PANDAS**

6. TÌM HIỂU ĐỐI TƯỢNG SERIES

In [ ]:
import pandas as pd
a = pd.Series([1., 2., 3.])
print('Series a:\n', a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print('\nSeries b với index chữ:\n', b)
print('First value (truy cập bằng nhãn a):', b['a'])

calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print('\nSeries từ Dictionary:\n', myvar)

Series a:
 0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0

Series b với index chữ:
 a    1.0
b    2.0
c    3.0
dtype: float64
First value (truy cập bằng nhãn a): 1.0

Series từ Dictionary:
 day1    420
day2    380
day3    390
dtype: int64


7. TẠO ĐỐI TƯỢNG DATAFRAME


In [ ]:

#  Chuyển từ Numpy sang Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

#  Chuyển ngược từ Pandas sang Numpy
numpy_h = np.array(df_h)
# Hoặc có thể dùng: numpy_h = df_h.values
print('Numpy array:\n', numpy_h)

import numpy as np
import pandas as pd

#  Tạo DataFrame từ Dictionary (Từ điển)
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print('DataFrame từ Dictionary:\n', df_dic)

#  Tạo mảng ngẫu nhiên 20x4 và đặt tên cột
# randn sinh số ngẫu nhiên theo phân phối chuẩn (có cả số âm và dương)
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

# In 5 dòng đầu tiên để kiểm tra
print('\n5 dòng đầu tiên của DataFrame ngẫu nhiên:\n', df.head())

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]
DataFrame từ Dictionary:
     Name  Age
0   John   30
1  Smith   40

5 dòng đầu tiên của DataFrame ngẫu nhiên:
         so1       so2       so3       so4
0  0.255744 -0.967186 -0.746401  3.274366
1 -0.527319  0.217416 -1.579113  0.101903
2  0.871590  1.135975 -0.047763  1.426484
3 -1.660008 -0.389469 -0.663182 -0.992998
4 -0.694296 -0.083393 -4.075758 -0.343513


7.1. Nối nhiều DataFrame


In [ ]:

# Tạo 2 DataFrame mẫu
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'], 'Age':[25, 30, 50]}, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'], 'Age':[26, 11]}, index=[3, 4])

# 1. Nối 2 DataFrame (theo chiều dọc)
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# 2. Xóa các hàng có giá trị trùng nhau ở cột Name
# Lưu ý: Smith xuất hiện ở cả df1 và df2, lệnh này sẽ xóa bớt 1 Smith
print('\nDrop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

# 3. Sắp xếp bảng theo giá trị cột Age (từ nhỏ đến lớn)
print('\nSort values in DataFrame\n', df_concat.sort_values('Age'))

# 4. Đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_pupil'})
print('\nRename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11

Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26

Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50

Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


7.2. Đọc dữ liệu từ CSV

In [ ]:
import pandas as pd

# Đường dẫn file vừa tạo nằm ngay thư mục gốc của Colab
path = 'Salary_Data.csv'

# Đọc file
df = pd.read_csv(path)

print("Nội dung file vừa tạo:")
print(df.head())

print("\nKích thước bảng (Dòng, Cột):", df.shape)

Nội dung file vừa tạo:
   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

Kích thước bảng (Dòng, Cột): (10, 2)


7.3. Gom nhóm dữ liệu DataFrame

In [ ]:
import pandas as pd
import numpy as np

# Tạo dữ liệu giả lập về các loài cá
data = {
    'Species': ['Bream', 'Bream', 'Roach', 'Roach', 'Pike', 'Pike', 'Bream'],
    'Weight': [242, 290, 120, 150, 500, 600, 340],
    'Height': [11.5, 12.4, 6.2, 7.1, 15.0, 16.5, 13.0]
}
df_csv = pd.DataFrame(data)

# 1. Tính trung bình (mean) cho tất cả các cột số theo từng loài cá
print("Trung bình theo loài:\n", df_csv.groupby(['Species']).mean())

# 2. Tìm trọng lượng nhỏ nhất (min) của từng loài cá
print("\nTrọng lượng nhỏ nhất theo loài:\n", df_csv.groupby(['Species'])['Weight'].min())

# 3. Gom nhóm theo nhiều cột (Loài và Chiều cao) rồi tìm trọng lượng nhỏ nhất
print("\nMin Weight theo Species và Height:\n", df_csv.groupby(['Species', 'Height'])['Weight'].min())

Trung bình theo loài:
              Weight  Height
Species                    
Bream    290.666667   12.30
Pike     550.000000   15.75
Roach    135.000000    6.65

Trọng lượng nhỏ nhất theo loài:
 Species
Bream    242
Pike     500
Roach    120
Name: Weight, dtype: int64

Min Weight theo Species và Height:
 Species  Height
Bream    11.5      242
         12.4      290
         13.0      340
Pike     15.0      500
         16.5      600
Roach    6.2       120
         7.1       150
Name: Weight, dtype: int64


In [ ]:
import pandas as pd

# Tạo dữ liệu giả lập
data = {
    'YearsExperience': [1.1, 1.3, 1.5, 2.0, 2.2, 2.9, 3.0, 3.2, 3.2, 3.7],
    'Salary': [39343, 46205, 37731, 43525, 39891, 56642, 60150, 54445, 64445, 57189]
}

# Chuyển thành DataFrame
df_sample = pd.DataFrame(data)

# Xuất ra file CSV
# Chúng ta sẽ lưu vào thư mục /content/ (thư mục mặc định của Colab)
df_sample.to_csv('Salary_Data.csv', index=False)

print("Đã tạo file Salary_Data.csv thành công!")

Đã tạo file Salary_Data.csv thành công!


### 8. BÀI *TẬP*

4. Tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [1]:
import numpy as np

# Tạo các mảng con
muoi_so_0 = np.zeros(10)
muoi_so_1 = np.ones(10)
muoi_so_5 = np.full(10, 5)

# Kết hợp (nối) chúng lại thành một mảng duy nhất
ket_qua = np.concatenate((muoi_so_1, muoi_so_0, muoi_so_5))

print("Mảng kết quả:")
print(ket_qua)

Mảng kết quả:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


5. Tạo mảng số nguyên chẵn từ [30, 70]

In [2]:

# Tạo mảng từ 30 đến 70 với bước nhảy là 2 để lấy số chẵn
mang_chan = np.arange(30, 71, 2)

print("Mảng số nguyên chẵn từ 30 đến 70:")
print(mang_chan)

Mảng số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**`LAP 2 TENSOR`**

3.1. Tensor 0-chiều

In [ ]:
import tensorflow as tf

# Tạo một Tensor hạng 0 (Rank 0 Tensor)
# Đây thực chất là một hằng số (Scalar)
rank_0_tensor = tf.constant(4)

print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf

# 1. Mặc định là số nguyên 32-bit (int32)
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# 2. Ép kiểu về số nguyên 16-bit (int16) - tốn ít bộ nhớ hơn
r1 = tf.constant(9, tf.int16)
print(r1)

# 3. Tạo Tensor số thực (float32) - dùng cho các phép toán có dấu phẩy
r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

# 4. Tạo Tensor kiểu chuỗi văn bản (string)
r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


3.2. Tensor 1-chiều

In [ ]:

# Tạo một Rank 1 Tensor (Vector) từ một danh sách số thực
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])

print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


3.3. Tensor 2-chiều (ma trận)

In [ ]:
rank_2_tensor = tf.constant([[1,2],
                            [3,4],
                            [5,6]], dtype=tf.float16

)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


3.4. Tensor n-chiều (nhiều trục)

In [ ]:
import tensorflow as tf

rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


3.5. Thuộc tính của tensor

In [ ]:
import tensorflow as tf

# --- Hình 8: Rank 3 Tensor ---
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
])

print(rank_3_tensor)
print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


3.6. Tạo tensor tự động gán giá trị 0 ban đầu

In [ ]:
t_zero = tf.zeros(10)
print(t_zero)
print('----------------')
t_2_zero = tf.zeros([3,3])
print(t_2_zero)
print('----------------')
t_3_zero = tf.zeros([3,3,5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
----------------
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
----------------
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


3.7. Tạo tensor tự động gán giá trị 1 ban đầu

In [ ]:
t_one = tf.ones(10)
print(t_one)
t_2_one = tf.ones([3, 3])
print(t_2_one)
t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


3.8. Tạo tensor tự động với giá trị bất kỳ

In [ ]:
t_1=tf.fill(3,10)
print(t_1)

t_2=tf.fill([3,3],9)
print(t_2)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


3.9. Tạo tensor 1-chiều với hàm linspace

In [ ]:
lin_tensor = tf.linspace(5.0,20.0,5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


3.10. Tạo tensor 1-chiều với hàm range

In [ ]:
range_tensor = tf.range(3.0,7.0,delta=0.5)
print(range_tensor)

range_tensor = tf.range(3.0,delta=0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


3.11. Tạo tensor với giá trị ngẫu nhiên

In [4]:
import tensorflow as tf

range_tensor = tf.random.normal([5])
print(range_tensor)

tf.Tensor([ 0.5523988  -0.00632371 -1.422774    1.2593284   0.3526749 ], shape=(5,), dtype=float32)


**Bài tập**

1. Tạo một tensor kích thước [2, 3] với các phần tử gán 0

In [6]:
import tensorflow as tf

# Tạo tensor 2x3 toàn số 0
tensor_1 = tf.zeros([2, 3])
print(tensor_1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


2. Tạo tensor có kích thước và dtype giống X nhưng phần tử gán 0

In [8]:
X = [[1, 2, 3], [4, 5, 6]]

# Tạo tensor giống X nhưng toàn số 0
tensor_2 = tf.zeros_like(X)
print(tensor_2)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


3. Tạo một tensor kích thước [3, 2] với các phần tử gán 5

In [9]:
# Tạo tensor 3x2 toàn số 5
tensor_3 = tf.fill([3, 2], 5)
print(tensor_3)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)
